MODEL_ARGS=(
    --swiglu
    --num-layers 48
    --hidden-size 8192
    --ffn-hidden-size 24576
    --num-attention-heads 64
    --group-query-attention
    --num-query-groups 8
    --max-position-embeddings 163840
    --use-rotary-position-embeddings
    --disable-bias-linear
    --normalization "RMSNorm"
    --norm-epsilon 1e-5
    --rotary-base 10000
    --vocab-size 256000
    --kv-channels 128
    --use-rope-scaling
    --rotary-scaling-factor 40.0
    --attention-dropout 0.0
    --hidden-dropout 0.0
    --untie-embeddings-and-output-weights
)
